/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.adzibilal.perpustakaan_kelompok2;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    public DashboardPanel() {
        initComponents();
        loadDataFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalBukuLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalMahasiswaLabel = new javax.swing.JLabel();
        totalTransaksiPeminjamanLabel = new javax.swing.JLabel();
        totalBukuDipinjamLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(785, 474));

        totalBukuLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalBukuLabel.setText("0");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Total Buku");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Total Mahasiswa");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Total Buku Dipinjam");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Total Transaksi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("DASHBOARD");

        totalMahasiswaLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalMahasiswaLabel.setText("0");

        totalTransaksiPeminjamanLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalTransaksiPeminjamanLabel.setText("0");

        totalBukuDipinjamLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        totalBukuDipinjamLabel.setText("0");

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(totalBukuLabel)
                            .addComponent(totalBukuDipinjamLabel))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalTransaksiPeminjamanLabel)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(totalMahasiswaLabel))))
                .addContainerGap(341, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBukuLabel)
                    .addComponent(totalMahasiswaLabel))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBukuDipinjamLabel)
                    .addComponent(totalTransaksiPeminjamanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        loadDataFromDatabase();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loadDataFromDatabase() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/db_perpustakaan", "root", "");
            Statement statement = connection.createStatement();

            // Menghitung total buku
            ResultSet bukuResult = statement.executeQuery("SELECT COUNT(*) AS total FROM buku");
            if (bukuResult.next()) {
                int totalBuku = bukuResult.getInt("total");
                totalBukuLabel.setText(String.valueOf(totalBuku));
            }

            // Menghitung total mahasiswa
            ResultSet mahasiswaResult = statement.executeQuery("SELECT COUNT(*) AS total FROM mahasiswa");
            if (mahasiswaResult.next()) {
                int totalMahasiswa = mahasiswaResult.getInt("total");
                totalMahasiswaLabel.setText(String.valueOf(totalMahasiswa));
            }

            // Menghitung total buku dipinjam
            ResultSet bukuDipinjamResult = statement.executeQuery("SELECT COUNT(*) AS total FROM detail_peminjaman");
            if (bukuDipinjamResult.next()) {
                int totalBukuDipinjam = bukuDipinjamResult.getInt("total");
                totalBukuDipinjamLabel.setText(String.valueOf(totalBukuDipinjam));
            }

            // Menghitung total transaksi peminjaman
            ResultSet transaksiPeminjamanResult = statement.executeQuery("SELECT COUNT(*) AS total FROM peminjaman");
            if (transaksiPeminjamanResult.next()) {
                int totalTransaksiPeminjaman = transaksiPeminjamanResult.getInt("total");
                totalTransaksiPeminjamanLabel.setText(String.valueOf(totalTransaksiPeminjaman));
            }

            statement.close();
            connection.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel totalBukuDipinjamLabel;
    private javax.swing.JLabel totalBukuLabel;
    private javax.swing.JLabel totalMahasiswaLabel;
    private javax.swing.JLabel totalTransaksiPeminjamanLabel;
    // End of variables declaration//GEN-END:variables
}
